const SPACER = 'SPACER'

const ERROR = 'ERROR'

const ERROR_DIDNT_BEGIN = 'ERROR_DIDNT_BEGIN'
const ERROR_PARSER_FAILED = 'ERROR_PARSER_FAILED'

const IGNORE = 'IGNORE'

const WORD = 'WORD'
const INTEGER = 'INTEGER'

module.exports = {
  SPACER,
  ERROR,
  ERROR_DIDNT_BEGIN,
  ERROR_PARSER_FAILED,
  IGNORE,
  WORD,
  INTEGER,
}
